[package]
name = "rust-unity-plugin-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
name = "my_rust_plugin_1"
crate-type = ["dylib"]